export const refs = {
  searchFormElement: document.querySelector('#search-form'),
  searchInputElement: document.querySelector('#search-input'),
  main: document.querySelector('#main'),
  watchedBtn: document.querySelector('#watched-button'),
  queueBtn: document.querySelector('#queue-button'),
  loader: document.querySelector('#loader'),
  openModal: document.querySelector('.open-modal-team'),
  closeModal: document.querySelector('.close-modal-team'),
  teamBackdrop: document.querySelector('.backdrop-modal'),
  teamModal: document.getElementsByClassName('team__modal'),
  previousButton: document.querySelector('#previous-btn'),
  nextButton: document.querySelector('#next-btn'),
  paginationList: document.querySelector('#pagination'),
  userWatched: document.querySelector('#user-watched-btn'),
  userQueue: document.querySelector('#user-queue-btn'),
};
